countries_info = [
    {"code": 32, "name": "Belgium", "currency": "€", "language": "French"},
    {"code": 62, "name": "Indonesia", "currency": "Rp", "language": "Indonesian"},
    {"code": 42, "name": "Czechia", "currency": "Kč", "language": "Czech"},
    {"code": 49, "name": "Germany", "currency": "€", "language": "German"},
    {"code": 359, "name": "Bulgaria", "currency": "лв", "language": "Bulgarian"},
    {"code": 33, "name": "France", "currency": "€", "language": "French"},
    {"code": 48, "name": "Poland", "currency": "zł", "language": "Polish"},
    {"code": 91, "name": "India", "currency": "₹", "language": "Hindi, English"},
    {"code": 40, "name": "Romania", "currency": "lei", "language": "Romanian"},
    {"code": 52, "name": "Mexico", "currency": "$", "language": "Spanish"},
    {"code": 44, "name": "United Kingdom", "currency": "£", "language": "English"},
    {"code": 34, "name": "Spain", "currency": "€", "language": "Spanish"},
    {"code": 43, "name": "Austria", "currency": "€", "language": "German"},
    {"code": 90, "name": "Turkey", "currency": "₺", "language": "Turkish"},
    {"code": 60, "name": "Malaysia", "currency": "RM", "language": "Malay"},
    {"code": 351, "name": "Portugal", "currency": "€", "language": "Portuguese"},
    {"code": 39, "name": "Italy", "currency": "€", "language": "Italian"},
    {"code": 1, "name": "United States", "currency": "$", "language": "English"},
    {"code": 593, "name": "Ecuador", "currency": "$", "language": "Spanish"},
    {"code": 57, "name": "Colombia", "currency": "$", "language": "Spanish"},
    {"code": 51, "name": "Peru", "currency": "S/", "language": "Spanish, Quechua"},
    {"code": 234, "name": "Nigeria", "currency": "₦", "language": "English"},
    {"code": 63, "name": "Philippines", "currency": "₱", "language": "Filipino, English"},
    {"code": 40, "name": "Romania", "currency": "lei", "language": "Romanian"},
    {"code": 39, "name": "Italy", "currency": "€", "language": "Italian"},
    {"code": 84, "name": "Vietnam", "currency": "₫", "language": "Vietnamese"},
    {"code": 30, "name": "Greece", "currency": "€", "language": "Greek"},
    {"code": 56, "name": "Chile", "currency": "$", "language": "Spanish"},
    {"code": 370, "name": "Lithuania", "currency": "€", "language": "Lithuanian"},
    {"code": 504, "name": "Honduras", "currency": "L", "language": "Spanish"},
    {"code": 386, "name": "Slovenia", "currency": "€", "language": "Slovene"},
    {"code": 359, "name": "Bulgaria", "currency": "лв", "language": "Bulgarian"},
    {"code": 30, "name": "Greece", "currency": "€", "language": "Greek"},
    {"code": 66, "name": "Thailand", "currency": "฿", "language": "Thai"},
    {"code": 36, "name": "Hungary", "currency": "Ft", "language": "Hungarian"},
    {"code": 502, "name": "Guatemala", "currency": "Q", "language": "Spanish"},
    {"code": 66, "name": "Thailand", "currency": "฿", "language": "Thai"},
    {"code": 84, "name": "Vietnam", "currency": "₫", "language": "Vietnamese"}
]