countries_info = [
    {"code": "BE", "name": "Belgium", "currency": "€", "language": "French"},
    {"code": "ID", "name": "Indonesia", "currency": "Rp", "language": "Indonesian"},
    {"code": "CZ", "name": "Czechia", "currency": "Kč", "language": "Czech"},
    {"code": "DE", "name": "Germany", "currency": "€", "language": "German"},
    {"code": "BG", "name": "Bulgaria", "currency": "лв", "language": "Bulgarian"},
    {"code": "FR", "name": "France", "currency": "€", "language": "French"},
    {"code": "PL", "name": "Poland", "currency": "zł", "language": "Polish"},
    {"code": "IN", "name": "India", "currency": "₹", "language": "Hindi, English"},
    {"code": "RO", "name": "Romania", "currency": "lei", "language": "Romanian"},
    {"code": "MX", "name": "Mexico", "currency": "$", "language": "Spanish"},
    {"code": "GB", "name": "United Kingdom", "currency": "£", "language": "English"},
    {"code": "ES", "name": "Spain", "currency": "€", "language": "Spanish"},
    {"code": "AT", "name": "Austria", "currency": "€", "language": "German"},
    {"code": "TR", "name": "Turkey", "currency": "₺", "language": "Turkish"},
    {"code": "MY", "name": "Malaysia", "currency": "RM", "language": "Malay"},
    {"code": "PT", "name": "Portugal", "currency": "€", "language": "Portuguese"},
    {"code": "IT", "name": "Italy", "currency": "€", "language": "Italian"},
    {"code": "US", "name": "United States", "currency": "$", "language": "English"},
    {"code": "EC", "name": "Ecuador", "currency": "$", "language": "Spanish"},
    {"code": "CO", "name": "Colombia", "currency": "$", "language": "Spanish"},
    {"code": "PE", "name": "Peru", "currency": "S/", "language": "Spanish, Quechua"},
    {"code": "NG", "name": "Nigeria", "currency": "₦", "language": "English"},
    {"code": "PH", "name": "Philippines", "currency": "₱", "language": "Filipino, English"},
    {"code": "RO", "name": "Romania", "currency": "lei", "language": "Romanian"},
    {"code": "IT", "name": "Italy", "currency": "€", "language": "Italian"},
    {"code": "VN", "name": "Vietnam", "currency": "₫", "language": "Vietnamese"},
    {"code": "GR", "name": "Greece", "currency": "€", "language": "Greek"},
    {"code": "CL", "name": "Chile", "currency": "$", "language": "Spanish"},
    {"code": "LT", "name": "Lithuania", "currency": "€", "language": "Lithuanian"},
    {"code": "HN", "name": "Honduras", "currency": "L", "language": "Spanish"},
    {"code": "SI", "name": "Slovenia", "currency": "€", "language": "Slovene"},
    {"code": "BG", "name": "Bulgaria", "currency": "лв", "language": "Bulgarian"},
    {"code": "GR", "name": "Greece", "currency": "€", "language": "Greek"},
    {"code": "TH", "name": "Thailand", "currency": "฿", "language": "Thai"},
    {"code": "HU", "name": "Hungary", "currency": "Ft", "language": "Hungarian"},
    {"code": "GT", "name": "Guatemala", "currency": "Q", "language": "Spanish"},
    {"code": "TH", "name": "Thailand", "currency": "฿", "language": "Thai"},
    {"code": "VN", "name": "Vietnam", "currency": "₫", "language": "Vietnamese"}
]
